name: Environment variables
on: push
jobs:
  runs-on: ubuntu-latest
  env:
    BRANCH: main
  steos:
    - runs: echo "${{BRANCH}}
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH }}
